### ISSUE TITLE
fuseiso

### ISSUE THREAD

**Issue by TMTYD** [hasse69/rar2fs#117]
Hi

is it somehow possible to combine rar2fs with fuseiso?

Because sometimes also contain packed files, iso or img files.

I have already tried rar2fs with --img-type or --show-comp-img, unfortunately without success.

**Comment by hasse69** [comment]
You need to be more clear what exactly your problem is.
Is it getting _.iso_ files to show up in directory listings such as `ls` or is it extraction of them that does not work?

**Comment by TMTYD** [comment]
But the ISO files are displayed, only I thought that they are also provided so that Plex finds them too.

Unfortunately, that is not the case, is there a way to combine that with fuseiso?

**Comment by hasse69** [comment]
Is this not the answer to your question?

https://support.plex.tv/articles/201358273-converting-iso-video-ts-and-other-disk-image-formats/

**Comment by TMTYD** [comment]
Thanks for your answer, this post I have already found.  Is not it possible that rar2fs the folder with the rar files mounts and then the ISO file mounts?

**Comment by hasse69** [comment]
No, it does not matter if you mount the ISO or not.
Unless the ISO image contains files like .avi, .mkv, .mp4 or any other video format containers that PLEX supports they cannot be used directly and must be converted. From the link I posted:

“Plex does not support the use of ISO, IMG, Video_TS, BDMV, or other “disk image” formats. If you wish to use those with Plex, you should convert them to a compatible format.“

But to answer your original question, yes you can use fuseiso on top of rar2fs (stacking) to mount image files. But if they are compressed it is very unlikely they will read properly.

Unless you have some other concerns or questions regarding rar2fs I would like to close this issue since it actually has nothing to do with mounting RAR files.

**Comment by TMTYD** [comment]
Ok thanks, it's alright when you close the topic.
