### ISSUE TITLE
Exclude wildcards

### ISSUE THREAD

**Issue by braderhart** [hasse69/rar2fs#134]
I am still pretty new to rar2fs. Is there any way to use wildcards to exclude files or directories containing a word that exists in multiple folders from being mounted? What about excluding compressed archives?

The reason I am creating an issue is because I couldn't find documentation explaining this.

**Comment by hasse69** [comment]
Sorry for late response, for obvious reasons things have been a bit upside down lately.

> The reason I am creating an issue is because I couldn't find documentation explaining this.

The simple answer is that there is no such documentation because there is no such feature.
The file exclusion that you get from the `--exclude` option is more about what contents outside of RAR files that should not be searched for inside it either. Normally that can be file browser specific file etc. 

The mount you do when using rar2fs is very close to a simple bind mount. It replicates the source files system completely with the addition of expanding files inside RAR archives. Having filters to hide things on the source file system would work against the intended design of rar2fs,
But then you are also not 100% clear what you wish to filter? Is it things outside of RAR files or the RAR files themselves? In the latter case I must ask what is the use case for wanting to do that? 
If you wish to have filtering on top of rar2fs I would search for some other FUSE file system that has that as its primary objective. Stacking FUSE file systems on top of each other is a very common approach to gain multiple extension to the standard file system.

**Comment by hasse69** [comment]
Unless there is something more you wish to add I would like to close this issue soon.

**Comment by braderhart** [comment]
@hasse69 I am looking to filter RAR files themselves. For example, if the subtitles are compressed, but the video is not, which is common for many scene releases—then in order to quickly access a video stored in the cloud using an rclone mount, I wouldn't want to decompress the subtitles. It would be nice to exclude them. Again, I understand there not being ideal, but this is how most scene releases are distributed and every optimization helps.

**Comment by hasse69** [comment]
Again. I fail to see the issue here, sorry.
>>>  I wouldn't want to decompress the subtitles.

If you do not wish to extract the file then don't? In what way would a filter help here? You extract what you chose to extract, nothing else. There is no extraction going on unless you actually try to read data from a file. The folder lookup (collecting RAR header meta data) is something else and also done only once and subsequent queries are picked from the cache.

**Comment by braderhart** [comment]
@hasse69 For some reason I thought that it was actually extracting the RAR files (subtitles), instead of merely reading the metadata. I don't think this is much of a concern now that I know. Thanks for explaining.

**Comment by hasse69** [comment]
AFAIK the files you are referring to usually comes in two level archives  (RAR in RAR). For that to even work you need to stack rar2fs filesystems since only one level is supported for each mount.

**Comment by hasse69** [comment]
I will close this issue now since I do not think there is much more to add.
