### ISSUE TITLE
Mount only the content of the rar archive

### ISSUE THREAD

**Issue by ossii79** [hasse69/rar2fs#150]
Is there any way to mount only the content of the archive, not anything outside of it?
In situations where you have:
Maindir
  SomeInfoFile
  SomeDir/WithSomeInfo
  something.rar (something.mkv split)
  something.r01 (something.mkv split)
  something.r02 (something.mkv split)

When mounting with rar2fs I want the mount point to show:
Maindir
  something.mkv

**Comment by hasse69** [comment]
The purpose of rar2fs is to mimic the source file system as if you had extracted all your archives inline.
There is currently no support for  filtering or flattening of the directory structure since that would be in direct conflict with the above. Besides, there are most likely file systems out there that can do the job a lot better than rar2fs would ever be able to, like this one https://github.com/gburca/rofs-filtered, You can stack as many FUSE file systems as you want.
