### ISSUE TITLE
RAR2FS does'nt always unpack everything in a file

### ISSUE THREAD

**Issue by aliak74** [hasse69/rar2fs#195]
I have an file that have two different *.mkv in it. Only one of them is showing in the memfs drive.
This is how i am making the drive:
rar2fs -o allow_other --seek-length=1 /cygdrive/D/xxx /cygdrive/Z/xxx

I have other issues using this method as well. I am running a jellyfinserver, and it seems that the drive sometimes looses some of the folders its "extracting" to the remote/second path. If i often to a library check on jellyfin, i suddenly can lose the second path/drive from the library. I cannot be 100% sure what is going on here, but i have seen several times that the cygdrive is suddenly slow and then loses one of the folders. When its slow i check the task manager, i can see that the memfs takes up a lot of RAM on the computer. Like its some issue with it.

I can document some of this later if its interesting to look at.

**Comment by hasse69** [comment]
There are several reasons to why certain files might not show up properly. I think the first thing to do here is to verify the same archive mounted on some native Linux host. This to conclude if this is really related to rar2fs or something with the environment, such as Cygwin, memfs and/or permissions etc etc

**Comment by aliak74** [comment]
I understand. I will try first to re-install/reset Cygwin and then memfs. Permissions should be suitable, but you never know. So I can check that as well. I don't have any native Linux host on this computer.

**Comment by hasse69** [comment]
One question is of course if this is a RAR volume or a single archive? If you have multiple files contained in a RAR volume using a seek length of 1 might not be adequate to find meta data for the second file.

**Comment by aliak74** [comment]
This is multiple files contained in a RAR volume.
What do you suggest as seek lenght? Can i just remove it and use default? Perhaps i have not setup this right. I just find someone on reddit telling people to use this as setting for similar or same use.

Another thing: I am using this for jellyfin media server. And i have a problem that the media library does not consider the changes coming from my virtual drive: For example a new movie coming in, will not give the right feedback to the media server. I think i found out when googling this issue that rar2fs does not support smart functions if i remember correctly. Do you have a workaround to this issue as well? What i did as workaround was to put in a automatic task in the media server that each 15 min checks the library for changes. But this seems not to work so well. I have experienced that jellyfin crashes, or that files/folder are suddenly gone on the virtual drive and that jellyfin then removes them right away since it checks for changes quite often.

**Comment by hasse69** [comment]
Did you read the rar2fs man page? The seek-length option is described there. You can remove the option entirely to see if that makes your missing file show up. If it does you can then configure rar2fs to use explicit values for seek-length per archive. Again, it is all described in the man page.

Regarding your other problem. I have no experience with the media server you mention. But I have had similar questions from other users regarding other media servers. Common among most of them is that they monitor the mount point for changes and not the source folder. If you add new files to your source folder nothing will tell rar2fs to "remount" and update/refresh. This has nothing to do with "smart functions", it is a matter of how much effort and resources you wish to waste having the file system auto-detect changes. The trick here is to write any new .rar files to the rar2fs mount point instead of to the source file system. In that way rar2fs will detect updates to the mount point and a media server monitoring it should also detect such.

**Comment by aliak74** [comment]
No, I didn't know about it until now. I will take a look.

Maybe I don't understand you fully on the media library thing. I always had my server check the rar2fs mount point when it comes to RAR-ed content. But what you are telling me is that when changes are made to the source of the file/dir, the virtual drive doesn't change accordingl?. I am quite sure I've seen it change itself instantly or at least relatively fast several times. But you say i have to re-mount the drive each time, or write rar files directly to virtual drive? I think I must have understood wrongly here.

**Comment by hasse69** [comment]
No, you should not remount. The problem is that media servers on eg Linux usually utilize functions like fsnotify etc to detect changes. But that requires the actual action performed to be against the monitored file system or else Kernel will not react. Updating the source folder (which is not monitored) will not trigger the change. That said, rar2fs will detect updates (on next access) since it will invalidate the cached information but that does not get through to the kernel. I know of no function available for user-space to force kernel into detecting a change on virtual file system level. But if you instead make your mount read/write and write your RAR archives to the mount point, both rar2fs and kernel would see the change. But how this works in Windows/cygwin is unknown to me. You probably need to check with the author of memfs.

**Comment by aliak74** [comment]
I dont know what happened, but suddenly i cant mount cygdrives anymore.

I get this one, "Cannot create WinFsp-FUSE file system: Invalid mount point" when running commands that worked earlier.

I think its the temp variable (PATH) in windows that is not correct anymore. I can access the cygdrive directly from cygwin64 but not from windows cmd. Ive had some issues on this windows and could be corrupted files that i rebuilt and some config was deleted.
But i tried rebuilding everything from this guide https://github.com/hasse69/rar2fs/wiki/Windows-HOWTO
Can't see what i missed.

![RemoteDesktopManager_yxqtqmoE6a](https://github.com/user-attachments/assets/b0be6d42-40af-42ed-8273-76400a29ced6)


Edit: Nevermind, i checked your setup guide again and had skipped an important step on the way. Its working now :D Thanks for all the work creating this guide by the way.

**Comment by aliak74** [comment]
Now my topic issue with just one file extracted in the mounted drive is working.

Thanks so much with helping me understanding how it works.

Now i just have to try and get the file updating process to work optimally for my jellyfin media server setup.

**Comment by hasse69** [comment]
Can this issue/topic be closed?

**Comment by aliak74** [comment]
Yes, thank you for your help.

tir. 17. sep. 2024 kl. 13:40 skrev hasse69 ***@***.***>:
