### ISSUE TITLE
Real Time Monitoring (inotify) with Rar2FS?

### ISSUE THREAD

**Issue by aliak74** [hasse69/rar2fs#197]
Hi,

is this supported? 
I talked with you earlier about Jellyfin not being to able to see updates on the file systems created using rar2fs.
I checked now and it says that only certain file systems support this.
Is it possible to set this up for rar2fs?

Info on this topic here: https://jellyfin.org/docs/general/administration/troubleshooting/#real-time-monitoring

**Comment by hasse69** [comment]
https://github.com/libfuse/libfuse/issues/328

There were some work on this but I really have not followed the progress here at all in the last couple of years. So I have no clue about the status of these patches and what requirements it would put on the actual implementation itself in rar2fs. I think you need to start your own investigation and if you find something useful please report back. Also this might be something supported by the later fuse3, but rar2fs does not support it and there is currently no plan to do so either.

**Comment by hasse69** [comment]
https://github.com/hasse69/rar2fs/issues/32

You can also read this rather long conversion regarding a similar topic. At the end of the day, it should only be a matter of writing your new files to the mount point rather than the source folder and inotify should kick in as expected.

**Comment by aliak74** [comment]
@hasse69 Hi again.

[Do you have any idea how to do what this person in this comment is telling about? ](https://emby.media/community/index.php?/topic/51496-real-time-monitoring-not-finding-anything/#findComment-941575)

Cloning the rar2fs fuse mount, and then adding that clone to the library of media server. According to that person, the clone have the real time monitoring features.

I searched and I searched but i can't find anything yet. I am probably looking at this with the wrong angle.

**Comment by hasse69** [comment]
No, I have no clue really what they are taking about.
But did you ever try to write your new files to the mount point and not the source folder? Did that still not help?
I am pretty sure this was tested some time back with inotify on the mount point and it worked. There has to be an actual change made to the mount point through FUSE to wake it up. Writing new files to the source file will not trigger such events for two reasons:

1) the source folder is not what is monitored 
2) Files detected by rar2fs in the source folder that are new will internally be resolved into the mount point but is completely bypassing the entire FS stack

**Comment by aliak74** [comment]
My mount point is where the library point to on RARed releases.
Not sure how i could write new files to the mount point. As all changes are done to the source directories.
What do you mean its bypassing entire FS stack?

**Comment by hasse69** [comment]
Yes I know you monitor the mount point but the mount point can be mounted read/write and then you can write .rar files to the mount point and they will become resolved automatically, thus you will never see the actual .rar files but the write will still go through the kernel and FUSE, which will trigger inotify since there is a modification on file system level. If rar2fs detects a change due to updates in the source folder, it is not the same thing since that will only affect stat() like calls, but nothing below rar2fs (kernel/FUSE) will spot the change. That would require that the user-space file system could signal the FUSE library and indirectly the kernel that something was modified. I know of no such interface today. There were talks about it some long time ago but I am not sure it ever made it further than FUSE prototypes and discussions.

**Comment by aliak74** [comment]
If i send all the rar files of a release into the mount point, will the rar files be unpacked there but be kept as normal in the source folder?

**Comment by hasse69** [comment]
Yes

**Comment by aliak74** [comment]
Thank you. I will try this :)
