### ISSUE TITLE
rar2fs should try it's best to open archives if an option is passed

### ISSUE THREAD

**Issue by KyleSanderson** [hasse69/rar2fs#52]
At the moment alternatives like rarfilesource happily continue along if any parts of an archive are missing (beginning, middle, and end). It doesn't matter if the archives are corrupt either, alternatives to rar2fs continue along.

Continuing this from issue 50, it would be awesome if rar2fs had this functionality.

**Comment by hasse69** [comment]
Thanks for the enhancement suggestion. I will classify this as an enhancement since I do not believe bailing on corrupt/incomplete archives really is not the right thing to do. Blindly returning data that does not exist may or may not work depending on what data the archive is carrying and how it is expected to be returned. You mentioned media playback in issue #50, but if the first volume file does not exist, the chance of it working is very slim since the file magic is not available. Returning dummy data at reads from archives that does not otherwise exist or return whatever corrupt information is there is doable and I will consider it and track the progress in this thread.

But considering the very limited time I have to spend on this project I need to prioritize the more serious issues/bugs reported and less narrow use cases. Currently that would be issue #49.
Sorry for any inconvenience this may cause you.

**Comment by hasse69** [comment]
To allow reading from incomplete and/or corrupt archives in store mode should be fairly easy. The first two volumes files must exist however since they contain key information to be able to properly calculate file offsets. If data cannot be accessed due to a missing file the read request(s) can return all 0. If that works or not is more about how the client will react on such data being returned. For compressed archives it is more tricky since extraction is mainly performed in libunrar and it *will* expect files to be present. I am not really sure that programs like `rarfilesource` can even coop with compressed archives?

**Comment by KyleSanderson** [comment]
I wouldn't worry about compression, for media and ilk rar is just used for file splitting.

**Comment by hasse69** [comment]
rar2fs does not really care what you chose to shove into those RARs. Simply saying that store mode is easy to handle, any level of compression is not. The thing that makes rar2fs differ from many other tools is that it handles also compressed archives (with some limitations). Many media files comes with compression as default, such as vobsub and cba.

**Comment by KyleSanderson** [comment]
Sorry for the confusion. The typical usage today with RARs is not to compress contents, but simply to split a single compressed file, like a .mkv, across multiple archives. This is because zip doesn't sanely support archive splitting and there are no reasonable tools to manipulate/maintain them. RAR is used as a storage container mostly, in store mode as you indicated.

Does this make a little more sense? :-)

**Comment by hasse69** [comment]
I do not think you need to explain yourself. I know very well how this works. But rar2fs is a *RAR* file system. It is not written for a specific contents. How it is used on the other hand is *user discretion*.

**Comment by hasse69** [comment]
I will add support for simply ignoring read errors in store mode. If that needs an options to enable/disable I have not yet decided. Hopefully this will improve things somewhat according to your request.

**Comment by hasse69** [comment]
Try this patch on a corrupt/incomplete archive, it should allow extraction but with bogus data.

[raw_read_v1.txt](https://github.com/hasse69/rar2fs/files/981175/raw_read_v1.txt)

**Comment by hasse69** [comment]
Patch covering also low level access problems

[raw_read_v2.txt](https://github.com/hasse69/rar2fs/files/981186/raw_read_v2.txt)

**Comment by KyleSanderson** [comment]
Thanks man, I'll try the patch when time permits (I have a bunch of travel coming up/on-going).

**Comment by hasse69** [comment]
Patch covering also low level access errors.

(patch v2 was broken and has been removed)
[raw_read_v3.txt](https://github.com/hasse69/rar2fs/files/981196/raw_read_v3.txt)

**Comment by hasse69** [comment]
New patch rebased on master
[raw_read_v4.txt](https://github.com/hasse69/rar2fs/files/1016522/raw_read_v4.txt)

**Comment by hasse69** [comment]
Since I am not getting any feedback on the patch I will consider this issue as resolved.
Case closed.
