### ISSUE TITLE
Support for .001 archives

### ISSUE THREAD

**Issue by lazuratus** [hasse69/rar2fs#55]
Would it be possible to add support for .001 archives? [(Example)](http://www.srrdb.com/release/details/Dragon.Ball.The.Path.To.Power.DVDRip.XviD-MiNT)

**Comment by hasse69** [comment]
Yes it is doable. The unrar library supports it. However, some internal lookup functions in rar2fs expects either classic .rNN format or newer .partN format. So there is a bit of work involved.

**Comment by hasse69** [comment]
I think I need to undo that statement.  I believe these files are created by some file splitting utility like hjsplit or similar, right? In that case they are not something that by definition is a RAR archive and thus rar2fs is not the tool to be used. Maybe there is some other file system that can "join" these files? In that case rar2fs can be mounted on top of it (stacked). But split files like this is not something rar2fs should handle.

**Comment by lazuratus** [comment]
No, those are not split by a splitting utility. You can accomplish this with WinRAR if you use `[x] Old style volume names` and than manually change the `Archive name` to `archive_name.001`. WinRAR will then create the `.002`, `.003`, etc. files if splitting is used instead of `.rNN`.

**Comment by hasse69** [comment]
Ok, then it is feasible. However, you also have to understand the difference between a tool like WinRAR and a file system like rar2fs. For WinRAR it is easy because it either creates the files in question or the user asks for extraction/test of a specific set of files. rar2fs cannot do that so easily. It has to take *all* files into consideration and if any extension could be used it would need to scan every single file to check header information for actual RAR files. But sure, it is possible to add .001-.nnn as recognized by rarfs, but then .000-.nnn would not work so question is if that really is a sane limitation or if it would only be silly? I guess you could even start with e.g. .002 and then it becomes even more obscure and impossible (or very hard at least) for rar2fs to calculate what file and certain offset belongs to. So, this all depends on how "standardized" this .001 extension really is. If all other permutations of .nnn is also commonly used then it is not worth the effort.

**Comment by hasse69** [comment]
I checked the code and I think this could be added without too much effort. Will see what I can do.

**Comment by hasse69** [comment]
Should now be resolved. Please report back after testing.

**Comment by lazuratus** [comment]
Just tested v1.23.1 and everything seems to be working 100%

Thank you!

**Comment by hasse69** [comment]
Thanks a lot for testing. Closing the issue.
