### ISSUE TITLE
Utilize more granular locking, or remove it entirely.

### ISSUE THREAD

**Issue by KyleSanderson** [hasse69/rar2fs#57]
file_access_mutex completely prevents any parallelization from occurring in rar2fs. This, from what I can tell from simply looking at perf, is the sole reason for slowness as described in issue #50.

**Comment by hasse69** [comment]
The file_access_mutex is there to protect the cache. Originally rar2fs was never designed for much parallelism at all, even the multi-threaded mode is by default disabled. So you/perf is most likely right in that it becomes a bottle-neck together with a few other things. It is possible to try to reduce the contention on the lock but you cannot remove it completely.  It is there for a reason. To be honest I have never spent that much time on it since performance has been good enough for most purposes.

**Comment by KyleSanderson** [comment]
Yeah, the product definitely works. It's just when there's any kind of serious seeking or directory listings that rar2fs is terribly slow.

**Comment by hasse69** [comment]
I will try to find some time to look into it. But I am not really convinced that the high look contention is the only problem here, if even a major one. Sure, it might affect the initial population of the cache, but once in there, it should perform fairly well. The --seek-length option has to be used for any decent performance. The real overhead if not used would be the need for scanning every single volume file. That comes with a huge penalty. Normally if you do e.g. ls -R on the entire mount point, the next time you access it I at least find the performance reasonably acceptable.

**Comment by hasse69** [comment]
I would be interesting to see some numbers from perf because my own measurements show a bit different results. Doing a ls -R on a mount point with rather many RAR files and volumes gave the below result.
1) Using default --seek-length (max), mutex locks, single threaded
6.51min (populate cache)
3.17min (cached)
2.34min (2 parallel ls)

2) Using --seek-lenght=1, mutex lock, single threaded
24s (populate cache)
9s (cached)
17s and 18s (2 parellel ls)

3) Using --seek-length=1, mutex lock, multi-threaded
24s (populate cache)
9s (cached)
17s,17s (2 parallel ls run 1)
17s,17s (2 parallel ls run 2)
17s,17s (2 parallel ls run 3)
25s,25s,25s (3 parallel ls)

4) Using seek-length=1. no mutex lock, multi-threaded
24s (populate cache)
9s (cached)
17s,17s (2 parallel ls run 1)
16s,16s (2 parallel ls run 2)
17s,16s (2 parallel ls run 3)
24s,24s,24s (3 parallel ls)

Judging from this result I would say the use of single-threaded or mutex locks are not really the bottle neck here. Sure, multi-threaded without mutex peforms slightly better than without mutex but that is expected. The mutex is there for a reason and it does not come for free. But the difference is rather small. Also running multi-threaded does not gain that much in my tests. It will probably benefit more the higher the number of parallel accesses you use, but the balance to me looks rather adequate. It was an active choice to go for a enforced single-threaded mode some time back. I think the reason was due to the fact that a user would not gain much at the cost of complexity. The mutex migh actually not be needed in single-threaded mode but it is there and it does not seem to really harm either.

**Comment by hasse69** [comment]
Unless there are any updates here I would like to close this issue soon.

**Comment by hasse69** [comment]
I think this issue can be closed.
A number of performance improvements has been made in the scope of fixing issue #49 by introducing  a directory cache to complement the file attribute cache.

**Comment by KyleSanderson** [comment]
@hasse69 thanks. If you could tag a release that would be wonderful.

**Comment by hasse69** [comment]
Not yet I am afraid :( There are some minor flaws that need to be solved first. Might have to revert parts of the solution because I am not sure it can be solved easily.
