### ISSUE TITLE
Where can I find unrar-lib?

### ISSUE THREAD

**Issue by nicoboss** [hasse69/rar2fs#58]
I'm on CentOS 7 x64 and using UNRAR 5.40 built from source using the tutorial from http://www.linuxfromscratch.org/blfs/view/svn/general/unrar.html /root/unrar is the source folder from which I've built unrar. /root/unrarlib-0.4.0/unrarlib is from http://www.unrarlib.org/download.html.

Now when I try to configure on by using:
/configure --with-unrar=/root/unrar --with-unrar-lib=/root/unrarlib-0.4.0/unrarlib

The following error appears:
checking rar.hpp usability... yes
checking rar.hpp presence... yes
checking for rar.hpp... yes
checking for RARGetDllVersion in -lunrar... no
configure: error:
            Can't find unrar library - add alternative library search path using
            --with-unrar-lib and rerun configure.

Sorry but I have no idea what library it needs so I gave him the path to the source folder unrarlib but probably I'm completely wrong because this library not even has a makefile. Can you please tell me what it needs for the argument --with-unrar-lib?

**Comment by magnub** [comment]
Use the unrar source from rar creators instead http://www.rarlab.com/rar/unrarsrc-5.4.5.tar.gz

**Comment by hasse69** [comment]
Correct. Either download the UnRAR source from rarlabs and build the library (not the unrar tool) and point configure to that. Or, in addition to building the unrar tool monolith, also build the library in /root/unrar

# make clean
# make lib

and then point both --with-unrar and --with-unrar-lib to it.

Remember that you need to copy/install the libunrar.so to somewhere in the system default library search path or rar2fs will otherwise not be able to locate it. The --with-unrar-lib is only for building towards a specific version matching the source code.

**Comment by nicoboss** [comment]
I was able to build rar2fs after using the correct unrar source, the normal make && make install and the make clean && make lib. And after coping the libunrar.so from /root/unrar to /lib64 everything worked like a charm. Thank you so much for your support and for making this amazing tool.
