### ISSUE TITLE
--max-seek-length

### ISSUE THREAD

**Issue by nubje** [hasse69/rar2fs#71]
Would there be possible to add, in combination with `--seek-length`, `--max-seek-length`?

So if you for instance would use it this:
`rar2fs --seek-length=1 --max-seek-length=10 /source /destination`
... it would try with one file, if it then fails to find headers continue to a second file and so on, up to, in this case, 10 volumes.
And if you would set it to 0, it would have the same behaviour as `--seek-length=0`.

**Comment by hasse69** [comment]
Sorry, but have you really stumbled into a case when this is needed? If so, please explain in detail how that use case look like. What confuses me a bit is this:

>... it would try with one file, if it then fails to find headers continue to a second file and so on, up to, in this case, 10 volumes.

Fact is that rar2fs would never accept a file without a header, because then it is not a RAR file by definition. All volume files have headers, not only the first one. Besides, there is an upcoming patch that will make sure first volume file always exist before even trying to read it which effectively makes --seek-length=1 start with the first file. Even today a value of 1 here in reality means 1+1 because at least two files needs to be scanned for proper offset estimation.

**Comment by nubje** [comment]
Well, it is kind of connected to being able to have individual seek-lengh per archive (as in #60), but instead of having to manually update the config file with new archives that need different settings, you specify a max-length. 

I used `--seek-length=1` and noticed that some files were missing, so changed it to `--seek-length=2`. Now I noticed other files that are missing, so instead of constantly increasing `--seek-length`, one could specify a limit on how many files to go through before giving up.
Before I noticed `--seek-length`, the indexing in Plex took hours, and would freeze up the playback. (I haven't tried `--seek-length=0` with cache, so that might still be better). 

If you think the upcoming patch will make it more reliable, even when using `--seek-length=1`, I am willing to give it a shot.

**Comment by hasse69** [comment]
Well, I think there is some confusion here? --seek-length tells you the maximum already.
As I said, all files have a header, and there will be files in those. Maybe not the complete list, but definitely some. So I cannot see how --seek-length=1 would ever not see anything. And how would it know when/if to continue? It would only be able to continue if a) no files were found (not applicable) or b) if the header is corrupt/missing (which it already does). So as i see it, a feature like this would have zero to no effect at all.

What you observe is exactly why --seek-length was introduced, to be able to see beyond the first header 
but not more than necessary for performance reasons. A length of 1 for some reason seems to be fairly adequate in 99% of the cases ;) But I agree that having a setting like this / archive make much more sense and that is the proper solution to your problem. Unfortunately I have had no time yet to continue that investigation due to other more serious issues that have to be prioritized.

The patch mentioned will not solve this, not at all. It will only make it 100% likely that you at least scan from the beginning and not from somewhere in the end or the middle. That is the problem with RAR volume headers, each file header only list the files having data resident in that particular volume. It might be many, it might be only one. It might not even be the file you *really* want. So the only way to make sure you really get them all is to not use --seek-length at all. And this is were the per archive settings could make a huge difference.

**Comment by nubje** [comment]
Yes, the confusion is that I have no idea how the archives are built up :D 

I'll up the `--seek-length` to 10, that should hopefully take care of it.

Regarding the per-archive-setting - that would need a remount of the filesystem, right?

And you can close this, since you've answered my questions. Thanks again! :)

**Comment by hasse69** [comment]
>Regarding the per-archive-setting - that would need a remount of the filesystem, right?

Not really sure what you mean here?
