### ISSUE TITLE
files detected as directories inside archives

### ISSUE THREAD

**Issue by magnub** [hasse69/rar2fs#76]
Hi

Since stepping up from 1.24.1 to 1.25.0 rar archives containing big ( > 1GiB) files list them as directories instead of files

(only big files inside archives are detected as directories)

I haven't had the chance to find the offending commit yet, just wanted to let you know

**Comment by hasse69** [comment]
Thanks. This one slipped through my testing. Cannot really say that it is obvious what caused this behavior though, All stats are set centrally in one function. Might be related to the new macros being used from unrarsrc.

**Comment by martikainen87** [comment]
Sometimes you're lucky, installed my new plexserver in a docker container yesterday and used the latest version of rar2fs to mount my archives, been scratching my head with why it didn't work untill i checked the   mount created with rar2fs and found that the files were detected as directories, and it led me here :) 

hasse: I'm guessing you dont have a solution right now, but could you describe on how to uninstall or downgrade rar2fs to the previous version? Since It's compiled from scratch I guess i manually have to fix a few things, but would be nice to get som pointers before i mess something up.

**Comment by hasse69** [comment]
Please check latest version on master. It should now have a fix for this problem.
Report back and if it works I will do a patch release of v1.25.0.

**Comment by magnub** [comment]
Works fine for me, files inside archives are files again :)

**Comment by hasse69** [comment]
Great! I take that as a go ahead :)
Sorry for the inconvenience this might have been causing you.

**Comment by magnub** [comment]
Yeah go ahead! =)
No worries, I stepped down to 1.24+ in the meantime, no harm done

**Comment by hasse69** [comment]
There is now a new version released.
Closing this issue.
