### ISSUE TITLE
.iso file into a rar package

### ISSUE THREAD

**Issue by baukland** [hasse69/rar2fs#91]
Hi there

Trying to find a way to use this rar2fs to open a .iso file inside a rar package. 
So is there a way to "unpack" .iso or img file inside a rar catalog...
Maby im doing it wrong. Normal packages works fine. But not if you have 2 levels like rar and iso inside.... Is that correct?

**Comment by hasse69** [comment]
Have you tried the —show-comp-img mount option? Sounds like that could be the issue. Also remember that accessing data inside an image file in a compressed archive may or may not work depending on the data access pattern used when the image is processed.

**Comment by baukland** [comment]
Hi there.

Ill do a test run. And ill get back to you.
But you can close it if you need to :).

Mvh
Aukland

Den fre. 20. apr. 2018, 23:20 skrev hasse69 <notifications@github.com>:

**Comment by baukland** [comment]
Hi there 

I been trying with this options. But it wont do how i want.
All my catalogs/rar_files opens if its a clean AVI/MKV and so on.
But i have a Catalogs/file.img. It doesent open it. I see the files has Video Audio catalog if i do it manually in some program.
Its the same with Catalog/file.iso. If the files under there is Audio_ts and Video_ts it wont "mount" it as that.

Maby thats not possible?

Auki

**Comment by hasse69** [comment]
Aha, I think you fooled me a bit here :) You cannot expect rar2fs to expose the contents of an image file (such a .iso). The image file is not a RAR archive. What rar2fs can help you with is to show the image file if it is part of e.g. a RAR archive volume or similar. It will then be made visible to other tools that can process it, such as a media player which might not be possible if it resides inside an archive.

As an example, if you mount folder x on y, and x has a file named foo.iso in the root, it will displayed as y/foo.iso. If x on the other hand has a RAR file (or volume) in the root containing a file called fee.iso, it will be displayed as y/fee.iso. But the contents of the ISO will never be displayed by rar2fs, it does not know what an ISO file is.

Let me know if this was the problem here. Otherwise I need to check if for some reason image file detection in rar2fs has broken on the way here. The only knowledge rar2fs has about image files is by name to virtually rename files from e.g. .img to .iso. To be honest I am not really happy with the existence of the --fake-iso feature but it was added a very very long time ago and it would be difficult to remove it now.

**Comment by baukland** [comment]
Yes. Thats correct explained.
Then it is not possible.
Thank you for clearing this up.

Auki

**Comment by hasse69** [comment]
You should checkout tools like this one:
https://sourceforge.net/projects/fuseiso/

You can stack as many FUSE filesystems on top of each other as you like.
Actually rar2fs can also be stacked to support multiple level of RAR files (RAR in RAR).
Simply mount to a folder `x` using rar2fs and mount `x` on `y` using e.g. `fuseiso`.

**Comment by baukland** [comment]
Will look it up.
Thanks
